=== tbagrel1/gmd/data_sources/annuaire.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT annuaire (personne+)>
<!ELEMENT personne (prenom, nom, telephone, age, ville, email)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ATTLIST personne id CDATA #REQUIRED>

=== tbagrel1/gmd/tp_jdbc/data_sources/espagne.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE annuaire SYSTEM "annuaire.dtd">
<annuaire>
    <personne id="1">
      <prenom>Patricia</prenom>
      <nom>Marquéz</nom>
      <telephone>017684536</telephone>
      <age>23</age>
      <ville>Madrid</ville>
      <email>patricia.marquez@mobistar.es</email>
    </personne>
    <personne id="2">
      <prenom>Carlos</prenom>
      <nom>Còntreras</nom>
      <telephone>0876354712</telephone>
      <age>34</age>
      <ville>Toledo</ville>
      <email>carlos.contreras@mobistar.es</email>
    </personne>
    <personne id="3">
      <prenom>Gabriela</prenom>
      <nom>Fernandez Ludoviz</nom>
      <telephone>0893847325</telephone>
      <age>18</age>
      <ville>Sevilla</ville>
      <email>gabriela.fernandez@mobistar.es</email>
    </personne>
    <personne id="4">
      <prenom>Alehandro</prenom>
      <nom>Fuentes</nom>
      <telephone>0826354712</telephone>
      <age>37</age>
      <ville>Barcelona</ville>
      <email>alehandro.fuentes@mobistar.es</email>
    </personne>
    <personne id="5">
      <prenom>Carolina</prenom>
      <nom>Machado</nom>
      <telephone>09784367121</telephone>
      <age>46</age>
      <ville>Madrid</ville>
      <email>carolina.machado@mobistar.es</email>
    </personne>
    <personne id="6">
      <prenom>Lolita Lagrandés</prenom>
      <nom>Urtado</nom>
      <telephone>0176438712</telephone>
      <age>22</age>
      <ville>Sevilla</ville>
      <email>lolita.urtado@mobistar.es</email>
    </personne>
    <personne id="7">
      <prenom>Lùis</prenom>
      <nom>Pedreira</nom>
      <telephone>0687237676</telephone>
      <age>49</age>
      <ville>Barcelona</ville>
      <email>luis.pedreira@mobistar.es</email>
    </personne>
    <personne id="8">
      <prenom>Huan</prenom>
      <nom>Cerrano</nom>
      <telephone>0498987752</telephone>
      <age>25</age>
      <ville>Madrid</ville>
      <email>huan.cerrano@mobistar.es</email>
    </personne>
    <personne id="9">
      <prenom>Pedròs</prenom>
      <nom>Picapiedra</nom>
      <telephone>0187873374</telephone>
      <age>28</age>
      <ville>Valencia</ville>
      <email>pedro.picapiedra@mobistar.es</email>
    </personne>
    <personne id="10">
      <prenom>Gustavo</prenom>
      <nom>Andreade</nom>
      <telephone>0999873267</telephone>
      <age>32</age>
      <ville>Valencia</ville>
      <email>gustavo.andreade@mobistar.es</email>
    </personne>
    <personne id="11">
      <prenom>Maria</prenom>
      <nom>Gònsaléz</nom>
      <telephone>0367668865</telephone>
      <age>21</age>
      <ville>Cordoba</ville>
      <email>maria.gonsalez@mobistar.es</email>
    </personne>
</annuaire>

=== tbagrel1/gmd/tp_jdbc/data_sources/italie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE annuaire SYSTEM "annuaire.dtd">
<annuaire>
    <personne id="1">
      <prenom>Giuseppe</prenom>
      <nom>Alfieri Lanterna</nom>
      <telephone>0813475678</telephone>
      <age>18</age>
      <ville>Firenze</ville>
      <email>giuseppe.alfieri@tim.it</email>
    </personne>
    <personne id="2">
      <prenom>Maurò</prenom>
      <nom>Torno Subito</nom>
      <telephone>0667849870</telephone>
      <age>24</age>
      <ville>Torino</ville>
      <email>mauro.torno@tim.it</email>
    </personne>
    <personne id="3">
      <prenom>Adriana</prenom>
      <nom>Lazzaro</nom>
      <telephone>0298768732</telephone>
      <age>28</age>
      <ville>Milano</ville>
      <email>adriana.lazzaro@tim.it</email>
    </personne>
    <personne id="4">
      <prenom>Livio</prenom>
      <nom>Marrocco</nom>
      <telephone>082365473805</telephone>
      <age>30</age>
      <ville>Caserta</ville>
      <email>livio.marrocco@tim.it</email>
    </personne>
    <personne id="5">
      <prenom>Gianni</prenom>
      <nom>Romario Il Grande</nom>
      <telephone>08167985412</telephone>
      <age>19</age>
      <ville>Napoli</ville>
      <email>gianni.romario@tim.it</email>
    </personne>
    <personne id="6">
      <prenom>Floriana</prenom>
      <nom>La bella</nom>
      <telephone>33578653409</telephone>
      <age>24</age>
      <ville>Firenze</ville>
      <email>floriana.chiaravalle@tim.it</email>
    </personne>
    <personne id="7">
      <prenom>Daniela</prenom>
      <nom>Rossini Lante della Rovere</nom>
      <telephone>09567549876</telephone>
      <age>35</age>
      <ville>Catania</ville>
      <email>daniela.rossi@tim.it</email>
    </personne>
    <personne id="8">
      <prenom>Daniela</prenom>
      <nom>Rossi</nom>
      <telephone>09567549876</telephone>
      <age>35</age>
      <ville>Catania</ville>
      <email>daniela.rossi@tim.it</email>
    </personne>
    <personne id="9">
      <prenom>Manuela</prenom>
      <nom>Valenti</nom>
      <telephone>08235645980</telephone>
      <age>22</age>
      <ville>Caserta</ville>
      <email>manuela.valenti@tim.it</email>
    </personne>
    <personne id="10">
      <prenom>Davide</prenom>
      <nom>Corradini</nom>
      <telephone>0678569809</telephone>
      <age>27</age>
      <ville>Roma</ville>
      <email>davide.corradini@tim.it</email>
    </personne>
    <personne id="11">
      <prenom>Marco</prenom>
      <nom>Trottà</nom>
      <telephone>0287657698</telephone>
      <age>37</age>
      <ville>Milano</ville>
      <email>marco.trotta@tim.it</email>
    </personne>
</annuaire>

=== tbagrel1/gmd/tp_jdbc/data_sources/angleterre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE annuaire SYSTEM "annuaire.dtd">
<annuaire>
    <personne id="1">
      <prenom>John</prenom>
      <nom>Smith Langley</nom>
      <telephone>097687531</telephone>
      <age>27</age>
      <ville>London</ville>
      <email>john.smith@bt.com</email>
    </personne>
    <personne id="2">
      <prenom>Jan</prenom>
      <nom>Asling</nom>
      <telephone>0789436721</telephone>
      <age>33</age>
      <ville>Fulham</ville>
      <email>jan.asling@bt.com</email>
    </personne>
    <personne id="3">
      <prenom>Barbara</prenom>
      <nom>Carberry</nom>
      <telephone>0743557612</telephone>
      <age>22</age>
      <ville>Lambeth</ville>
      <email>barbara.carberry@bt.com</email>
    </personne>
    <personne id="4">
      <prenom>Linda</prenom>
      <nom>Burrows Meth</nom>
      <telephone>0826354712</telephone>
      <age>25</age>
      <ville>London</ville>
      <email>linda.burrows@bt.com</email>
    </personne>
    <personne id="5">
      <prenom>Damian</prenom>
      <nom>Smith Arners</nom>
      <telephone>09784367121</telephone>
      <age>35</age>
      <ville>Kennington</ville>
      <email>damian.smith@bt.com</email>
    </personne>
    <personne id="6">
      <prenom>Elizabeth</prenom>
      <nom>Stone</nom>
      <telephone>0844568733</telephone>
      <age>20</age>
      <ville>Holborn</ville>
      <email>elizabeth.stone@bt.com</email>
    </personne>
    <personne id="7">
      <prenom>Ian</prenom>
      <nom>Macilwain</nom>
      <telephone>0589900045</telephone>
      <age>32</age>
      <ville>Fulham</ville>
      <email>ian.macilwain@bt.com</email>
    </personne>
    <personne id="8">
      <prenom>Christina</prenom>
      <nom>Russo</nom>
      <telephone>0534342256</telephone>
      <age>28</age>
      <ville>Hackney One</ville>
      <email>christina.russo@bt.com</email>
    </personne>
    <personne id="9">
      <prenom>Lyn</prenom>
      <nom>Lowe</nom>
      <telephone>0632454565</telephone>
      <age>30</age>
      <ville>London</ville>
      <email>lyn.lowe@bt.com</email>
    </personne>
    <personne id="10">
      <prenom>Emma</prenom>
      <nom>Lordan Belley</nom>
      <telephone>0756563412</telephone>
      <age>38</age>
      <ville>Holborn</ville>
      <email>emma.lordan@bt.com</email>
    </personne>
    <personne id="11">
      <prenom>Cindy</prenom>
      <nom>Lea</nom>
      <telephone>0588986712</telephone>
      <age>26</age>
      <ville>London</ville>
      <email>cindy.lea@bt.com</email>
    </personne>
</annuaire>
